title: "The Weekend"
author: "Sal"
description: "Made with <i style=\"color: #f45;\">patience</i>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%d %B, %Y"

remote_theme: niklasbuschmann/contrast@v2.11

# Layout

show_excerpts: true
show_frame: true         
show_sidebar: false     
minimal: false          
future: true

# Menu

navigation:                
  - {file: "index.html"}

external:                  # for available icons see fontawesome.com/icons
  - {title: Github, icon: github, url: "https://github.com/salchoman"}

# GitHub
domain: salcho.github.io       # force HTTPS by skipping the protocol
url: https://salcho.github.io  # base URL
baseurl: /

plugins:
 - jekyll-feed
 - jekyll-remote-theme
